# Generated by Django 5.2.1 on 2025-05-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                (
                    "processed_image",
                    models.ImageField(blank=True, null=True, upload_to="processed/"),
                ),
                (
                    "result_csv",
                    models.FileField(blank=True, null=True, upload_to="reports/csv/"),
                ),
                (
                    "result_xlsx",
                    models.FileField(blank=True, null=True, upload_to="reports/xlsx/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
