# Generated by Django 5.2.1 on 2025-05-14 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="processedimage",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="processedimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="processedimage",
            name="processed_image",
        ),
        migrations.RemoveField(
            model_name="processedimage",
            name="result_csv",
        ),
        migrations.RemoveField(
            model_name="processedimage",
            name="result_xlsx",
        ),
        migrations.RemoveField(
            model_name="processedimage",
            name="user",
        ),
        migrations.AddField(
            model_name="processedimage",
            name="image_file",
            field=models.ImageField(null=True, upload_to="results/"),
        ),
        migrations.CreateModel(
            name="DetectedROI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roi_file", models.ImageField(upload_to="results/rois/")),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "parent_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rois",
                        to="detector.processedimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                (
                    "processed_image",
                    models.ImageField(blank=True, null=True, upload_to="processed/"),
                ),
                (
                    "result_csv",
                    models.FileField(blank=True, null=True, upload_to="reports/csv/"),
                ),
                (
                    "result_xlsx",
                    models.FileField(blank=True, null=True, upload_to="reports/xlsx/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
