# Generated by Django 5.2.1 on 2025-05-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0002_rename_created_at_processedimage_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectedroi",
            name="x_max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="detectedroi",
            name="x_min",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="detectedroi",
            name="y_max",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="detectedroi",
            name="y_min",
            field=models.FloatField(null=True),
        ),
    ]
