# Generated by Django 5.2.1 on 2025-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0003_detectedroi_x_max_detectedroi_x_min_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedimage",
            name="original_file",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
