# Generated by Django 5.2.1 on 2025-05-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0004_processedimage_original_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedimage",
            name="is_created_by_auth_user",
            field=models.BooleanField(default=False),
        ),
    ]
