# Generated by Django 5.2.1 on 2025-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0005_processedimage_is_created_by_auth_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reports",
            name="image",
        ),
        migrations.RemoveField(
            model_name="reports",
            name="processed_image",
        ),
        migrations.AddField(
            model_name="reports",
            name="images",
            field=models.ManyToManyField(
                related_name="reports", to="detector.processedimage"
            ),
        ),
    ]
