# Generated by Django 5.2.1 on 2025-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "detector",
            "0006_remove_reports_image_remove_reports_processed_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
